### ISSUE TITLE
Light Dragon doesn't shrink

### ISSUE THREAD

**Issue by Venaf** [Scriptshatter/Elemental-Dragon#2]
Light dragon doesn't get smaller at level 2.  I looked through the code and I think the functions/triggers/layer_two mcfunction files have the size refresh in air and dark instead of dark and light.

**Comment by Scriptshatter** [comment]
Ah, I'll fix that in a moment.

**Comment by Venaf** [comment]
Another thing I ran into - not sure if it's intentional or not - light dragon with any other dragon is still vegetarian,

**Comment by Scriptshatter** [comment]
That is intentional.
